### PR TITLE
⚠️ CONFLICT! Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request: CONFLICT #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-ansible-role-with-test-user.git`](https://github.com/cisagov/skeleton-ansible-role-with-test-user.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

The `lineage/skeleton` branch has **one or more unresolved merge conflicts**
that you must resolve before merging this pull request!

## How to resolve the conflicts ##

1. Take ownership of this pull request by removing any other assignees.

1. Clone the repository locally, and reapply the merge:

    ```console
    git clone git@github.com:cisagov/ansible-role-cyhy-reports.git ansible-role-cyhy-reports
    cd ansible-role-cyhy-reports
    git remote add skeleton https://github.com/cisagov/skeleton-ansible-role-with-test-user.git
    git remote set-url --push skeleton no_push
    git switch develop
    git checkout -b lineage/skeleton --track origin/develop
    git pull skeleton HEAD
    git status
    ```

1. Review the changes displayed by the `status` command.  Fix any conflicts and
   possibly incorrect auto-merges.

1. After resolving each of the conflicts, `add` your changes to the
   branch, `commit`, and `push` your changes:

    ```console
    git add meta/main.yml molecule/default/molecule-no-systemd.yml 
    git commit
    git push --force --set-upstream origin lineage/skeleton
    ```

    Note that you may *append* to the default merge commit message
    that git creates for you, but *please do not delete the existing
    content*.  It provides useful information about the merge that is
    being performed.

1. Wait for all the automated tests to pass.

1. Check the "Everything is cool" checkbox below:

    - [x] ✌️ The conflicts in this pull request have been resolved.

1. Mark this draft pull request "Ready for review".

---

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Comment by jsf9k** [comment]
I can see from the output of `molecule converge && molecule -vv idempotence` that it is the flip-flopping between `pandas==0.23.3` ([as specified in this repo](https://github.com/cisagov/cyhy-reports/blob/a51656af071c91fdd8556da4731b026ac311ed65/setup.py#L64)) and `pandas=0.19.1` ([as specified in cisagov/ncats-webd](https://github.com/cisagov/ncats-webd/blob/20521a47863e3501426e6a0d34e80c44f14b16d8/setup.py#L31)) that is breaking idempotence:
```
$ molecule converge && molecule -vv idempotence

<snip>

TASK [ncats_webd : Install ncats-webd] *****************************************
task path: /home/jeremy_frasier/.cache/molecule/ansible-role-cyhy-reports/default/roles/ncats_webd/tasks/main.yml:24
changed: [debian9] => {"changed": true, "cmd": ["/usr/bin/pip2", "install", 
<snip>
"Installing collected packages: pandas", 
"  Found existing installation: pandas 0.23.3", 
"    Uninstalling pandas-0.23.3:", 
"      Successfully uninstalled pandas-0.23.3", 
"Successfully installed pandas-0.19.2"], 
"version": null, "virtualenv": null}

<snip>

TASK [ansible-role-cyhy-reports : Install cyhy-reports] ************************
task path: /home/jeremy_frasier/cisagov/ansible-role-cyhy-reports/tasks/main.yml:51
changed: [debian9] => {"changed": true, "cmd": ["/usr/bin/pip2", "install",
<snip>
"Installing collected packages: pandas", 
"  Found existing installation: pandas 0.19.2", 
"    Uninstalling pandas-0.19.2:", 
"      Successfully uninstalled pandas-0.19.2", 
"Successfully installed pandas-0.23.3"], 
"version": null, "virtualenv": null}
<snip>
```

@mcdonnnj and @dav3r, should we look at bumping [cisagov/ncats-webd](https://github.com/cisagov/ncats-webd) up to 0.23.0?

**Comment by dav3r** [comment]
> @mcdonnnj and @dav3r, should we look at bumping [cisagov/ncats-webd](https://github.com/cisagov/ncats-webd) up to 0.23.0?

Yes, I think that is what we should try first.

**Comment by jsf9k** [comment]
> > @mcdonnnj and @dav3r, should we look at bumping [cisagov/ncats-webd](https://github.com/cisagov/ncats-webd) up to 0.23.0?
> 
> Yes, I think that is what we should try first.

Are the `setup.py` and `requirements.txt` changes in cisagov/cyhy-reports#71 and cisagov/cyhy-reports#72 all I need to translate over to [cisagov/ncats-webd](https://github.com/cisagov/ncats-webd)?  I wasn't sure if there were possibly some package installations that needed to change inside Docker containers and/or AMIs as well.

**Comment by mcdonnnj** [comment]
> > > @mcdonnnj and @dav3r, should we look at bumping [cisagov/ncats-webd](https://github.com/cisagov/ncats-webd) up to 0.23.0?
> > 
> > 
> > Yes, I think that is what we should try first.
> 
> Are the `setup.py` and `requirements.txt` changes in [cisagov/cyhy-reports#71](https://github.com/cisagov/cyhy-reports/pull/71) and [cisagov/cyhy-reports#72](https://github.com/cisagov/cyhy-reports/pull/72) all I need to translate over to [cisagov/ncats-webd](https://github.com/cisagov/ncats-webd)? I wasn't sure if there were possibly some package installations that needed to change inside Docker containers and/or AMIs as well.

I think you only need to modify `setup.py` in that project.

**Comment by jsf9k** [comment]
> > > > @mcdonnnj and @dav3r, should we look at bumping [cisagov/ncats-webd](https://github.com/cisagov/ncats-webd) up to 0.23.0?
> > > 
> > > 
> > > Yes, I think that is what we should try first.
> > 
> > 
> > Are the `setup.py` and `requirements.txt` changes in [cisagov/cyhy-reports#71](https://github.com/cisagov/cyhy-reports/pull/71) and [cisagov/cyhy-reports#72](https://github.com/cisagov/cyhy-reports/pull/72) all I need to translate over to [cisagov/ncats-webd](https://github.com/cisagov/ncats-webd)? I wasn't sure if there were possibly some package installations that needed to change inside Docker containers and/or AMIs as well.
> 
> I think you only need to modify `setup.py` in that project.

Please see cisagov/ncats-webd#28.

**Review by jsf9k — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
LGTM!  Let's end this forever-Kraken! 🎉

**Comment by jsf9k** [comment]
> LGTM! Let's end this forever-Kraken! tada

I don't think [cisagov/skeleton-docker](https://github.com/cisagov/skeleton-docker) was ever taken care of, so the forever Kraken persists.  #treeofwoe

**Review by mcdonnnj — APPROVED** [review]
*It does the stuff.* :shipit:

**Pull request merged**
